//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAIL
    {
        public int ID { get; set; }
        public string ID_PRO { get; set; }
        public string NAME_CATE { get; set; }
        public string HEDIEUHANH { get; set; }
        public string SIZE { get; set; }
        public string WEIGHT { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
